---
networks:
  frontend:
    external: true
  backend:
    external: true
volumes:
  prometheus-data:
    driver: local
services:
  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: prometheus-prod-1
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus-prod-1-https.entrypoints=websecure
      - traefik.http.routers.prometheus-prod-1-https.rule=Host(`prometheus-prod-1.srv-prod-1.home.ragekuuhaku.cloud`)
      - traefik.http.routers.prometheus-prod-1-https.tls=true
      - traefik.http.routers.prometheus-prod-1-https.tls.certresolver=cloudflare
      - traefik.http.routers.prometheus-prod-1-https.middlewares=authentik-prod-1-middleware@file
    networks:
      - frontend
      - backend
    restart: unless-stopped
