---
networks:
  frontend:
    external: true
  backend:
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.11
    container_name: homepage-prod-1
    environment:
      - LOG_LEVEL=debug
      # - HOMEPAGE_VAR_PROXMOX_USERNAME=${HOMEPAGE_VAR_PROXMOX_USERNAME}
      # - HOMEPAGE_VAR_PROXMOX_PASSWORD=${HOMEPAGE_VAR_PROXMOX_PASSWORD}
      # - HOMEPAGE_VAR_TRUENAS_KEY=${HOMEPAGE_VAR_TRUENAS_KEY}
      - HOMEPAGE_VAR_PORTAINER_KEY=${HOMEPAGE_VAR_PORTAINER_KEY}
      # - HOMEPAGE_VAR_AUTHENTIK_KEY=${HOMEPAGE_VAR_AUTHENTIK_KEY}
      # - HOMEPAGE_VAR_HOMEASSISTANT_KEY=${HOMEPAGE_VAR_HOMEASSISTANT_KEY}
      - HOMEPAGE_VAR_JELLYFIN_KEY=${HOMEPAGE_VAR_JELLYFIN_KEY}
      - HOMEPAGE_VAR_RADARR_KEY=${HOMEPAGE_VAR_RADARR_KEY}
      - HOMEPAGE_VAR_SONARR_KEY=${HOMEPAGE_VAR_SONARR_KEY}
      - HOMEPAGE_VAR_PROWLARR_KEY=${HOMEPAGE_VAR_PROWLARR_KEY}
      - HOMEPAGE_VAR_BAZARR_KEY=${HOMEPAGE_VAR_BAZARR_KEY}
    volumes:
      - ./config:/app/config
      - ./app/public/images:/app/public/images
      - ./app/public/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage-prod-1-https.entrypoints=websecure
      - traefik.http.routers.homepage-prod-1-https.rule=Host(`homepage-prod-1.srv-prod-1.home.ragekuuhaku.cloud`)
      - traefik.http.routers.homepage-prod-1-https.tls=true
      - traefik.http.routers.homepage-prod-1-https.tls.certresolver=cloudflare
    networks:
      - frontend
      - backend
    restart: unless-stopped
