---
networks:
  frontend:
    external: true
  backend:
    external: true
services:
  twingate:
    container_name: twingate-connector-prod-1
    image: twingate/connector:1.70.0
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - TWINGATE_NETWORK=ragekuuhaku
      - TWINGATE_DNS=192.168.135.1
      - TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN}
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN}
      - TWINGATE_LOG_LEVEL=1
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
    networks:
      - frontend
      - backend
    restart: unless-stopped