---
networks:
  frontend:
    external: true
services:
  nginx:
    container_name: nginx-prod-1
    image: nginx:1.25.5-alpine
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-prod-1-http.entrypoints=web
      - traefik.http.routers.nginx-prod-1-http.rule=Host(`nginx-prod-1.srv-prod-1.home.ragekuuhaku.cloud`)
      - traefik.http.routers.nginx-prod-1-https.tls=true
      - traefik.http.routers.nginx-prod-1-https.tls.certresolver=cloudflare
      - traefik.http.routers.nginx-prod-1-https.entrypoints=websecure
      - traefik.http.routers.nginx-prod-1-https.rule=Host(`nginx-prod-1.srv-prod-1.home.ragekuuhaku.cloud`)
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/usr/share/nginx/html
    networks:
      - frontend
