---
networks:
  frontend:
    external: true

# volumes:
#   tvseries:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: addr=nas-prod-1.home.ragekuuhaku.cloud,rw,vers=4.2
#       device: ":/mnt/nas/data/app-pv/tvseries"
#   movies:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: addr=nas-prod-1.home.ragekuuhaku.cloud,rw,vers=4.2
#       device: ":/mnt/nas/data/app-pv/movies"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin-prod-1
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Makassar
      #- JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - ./library:/config
      - /mnt/data/app-pv/tvseries:/data/tvshows
      - /mnt/data/app-pv/movies:/data/movies
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin-prod-1-https.entrypoints=websecure
      - traefik.http.routers.jellyfin-prod-1-https.rule=Host(`jellyfin-prod-1.srv-prod-1.home.ragekuuhaku.cloud`)
      - traefik.http.routers.jellyfin-prod-1-https.tls=true
      - traefik.http.routers.jellyfin-prod-1-https.tls.certresolver=cloudflare
      - traefik.http.services.jellyfin-prod-1-svc.loadbalancer.server.port=8096
    restart: unless-stopped