---
services:
  postgres:
    container_name: pdb-prod-1
    image: postgres:17.0-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - backend
      - frontend
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  
  adminer:
    container_name: adminer-pdb-prod-1
    image: adminer:4.8.1
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer-pdb-prod-1-https.rule=Host(`adminer-pdb-prod-1.srv-prod-1.home.ragekuuhaku.cloud`)
      - traefik.http.routers.adminer-pdb-prod-1-https.entrypoints=websecure
      - traefik.http.routers.adminer-pdb-prod-1-https.tls=true
      - traefik.http.routers.adminer-pdb-prod-1-https.tls.certresolver=cloudflare
      - traefik.http.services.adminer-pdb-prod-1.loadbalancer.server.port=8080
      - traefik.http.services.adminer-pdb-prod-1.loadbalancer.server.scheme=http

networks:
  frontend:
    external: true
  backend:
    external: true
volumes:
  postgres-data:
