name: Update Docker Compose File

on:
  push:
    branches:
      - main
    paths:
      - "nginx/docker-compose.yaml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload new docker compose file
        uses: appleboy/scp-action@v0.1.7
        with:
          username: riot
          host: srv-prod-1.home.ragekuuhaku.cloud
          key: ${{ secrets.SSH_KEY }}
          source: "nginx/docker-compose.yaml"
          target: "/home/riot/docker/nginx/"
          strip_components: 1
