name: Update Docker Compose File

on:
  push:
    branches:
      - main
    paths:
      - "nginx/docker-compose.yaml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
